name: historias_a_medida
description: Um app de histórias personalizadas para pais criativos, permitindo que você crie narrativas únicas e especiais para seus filhos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  convex_bottom_bar: ^3.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gutter: ^1.0.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  google_generative_ai: ^0.4.3
  intl: ^0.19.0
  markdown_widget: ^2.3.2+6
  uuid: ^4.4.0
  hive_flutter: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
